language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
script:
  - npm run check:ci && npm run versiona
  - npm run coverage:ci

after_success:
- bash <(curl -s https://codecov.io/bash)